%YAML:1.0



DMatcher:
  # 实飞
  sat_map: "../../map/XA_L19_CUT/"
  # evelation_map: "../../map/elevation/"
  # dfeature_database_path: "../../map/localDFeature/"
  dfeature_type: 1
  dfeature_model_path:
    N: 2
    path_00: "/usr/local/sp.rknn"
    path_01: "/usr/local/sp.onnx"

  debug_dir: "../../debug_log/target/image/"
  zmq_image_match_address: "ipc:///tmp/image_match"
  zmq_image_feature_address: "ipc:///tmp/dmatch_feature"
  debug_show: 1
  ransac_threshold: 20

  threshold_ratio_for_search: 2.5

  search_top_n: 15
  # model:
  # 0 --- npu; 1 --- gpu
  device: 0
  MatchQuality:
    MaxPointNum: 30
    DistributionRatioThreshold: 8
    prior_pose_scale: 3.0
    ignore_pose_std_threshold: 100
    second_M_scale: 2.0
    second_std_scale: 0.5
    second_match_std_rx: 1.0
    second_match_std_ry: 1.0
    second_match_std_rz: 1.0

dmatcher_server_address: "ipc:///tmp/dmatch_target"


# warn
log_code: "70b02a7af8943c4ec6ae4012e4cc6b333033b4c03f5a68cb34caaa9939d39225"
# 不使用
fence_code: "867a35978e3b8eb4666634f1abf28cb131438ad217044e19af9385b36f34ec87"
