%YAML:1.0

#@@@@@@@@@@@@@@@@@@@@@@@ 外场修改1、是否存储相机图像数据？ @@@@@@@@@@@@@@@@@@@@@@@
# save_video_flag: 1 存图像   save_video_flag: 0   不存图像
save_video_flag: 0


#@@@@@@@@@@@@@@@@@@@@@@@ 外场修改2、是否全拒止？ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

lonlat_std_max_threshold: 1   # 1为半拒止  2000为全拒止   单位是米。

# 起飞点经度，类型为double，全拒止飞行时需修改为正确的起飞点经度
init_lon: 90
# 起飞点纬度，类型为double，全拒止时飞行需修改为正确的起飞点纬度
init_lat: 42.857930

plane_max_speed: 15        #飞行器最大飞行速度，单位：米每秒


#@@@@@@@@@@@@@@@@@@@@@@@ 外场修改3、配置图像和飞参数据获取方式 @@@@@@@@@@@@@@@@@@@
# 设置图像的来源，目前可配置如下三个参数 ：  
#          "ZMQ" ：通过ZMQ接收图像数据
#          "SDI" ：通过SDI获取图像
#          "USB" ：通过USB获取图像
ppdh_img_source: ZMQ


# 设置飞参数据的来源，目前可配置如下两个参数：
#           "SPT" :  通过硬件串口获取飞参数据
#           "ZMQ" :  通过ZMQ接收飞参数据
aircraft_param_source: "ZMQ"


#@@@@@@@@@@@@@@@@@@@@@@@ 外场修改4、其他导航方式选择 @@@@@@@@@@@@@@@@@@@@@@@@@@@@
is_INS_ava: 0     #高精度惯导是否可用？0，不可用；1，可用
is_KSG_ava: 0     #空速管是否可用？0，不可用；1，可用

Vn_KSG: 0.0
Ve_KSG: 0.0

# 平滑最大速度
smooth_max_speed: 50


#@@@@@@@@@@@@@@@@@@@@@@@ 外场修改5、相机图像采集的延时补偿，单位是毫秒 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
image_dealy_time: 0.0     


#@@@@@@@@@@@@@@@@@@@@@@@ 外场修改6、（空）惯导比例系数 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
ins_std_ratio: 0.2

# no_ins_std_ratio 无空惯导时，伪空惯导std， double
no_ins_std_ratio: 0.2

#@@@@@@@@@@@@@@@@@@@@@@@ 外场修改7、串口波特率 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
baud_rate: 921600





# =============================以下通常不修改========================
# =============================以下通常不修改========================
# =============================以下通常不修改========================
# =============================以下通常不修改========================
# =============================以下通常不修改========================
debug_log_file_path: "./trans_log/"   # 存储原始图像和飞参的路径

#初始位置的不确定范围，单位：米
lonlat_basic_std: 100       

# 起飞点基准高度，无GC图写0
basic_height: 0.0

# 每得到N次视觉定位成功的结果，进行一次人工对比判读，数据的正确性。调试用。
DEBUG_JUDGE: 100

# 开始计算起飞时间的高度阈值    单位：米   数据类型int
height_of_begin_cal_take_off_tm: 15

# 图像启动高度
send_frame_height_thres: 100

# is_CHALE:int   1 使用     0 不使用
is_CHALE: 1
# 数据类型double 
CLAHE_clip_limit: 2.0

# 云台类型:    0 - 没有云台     1 - 下视增稳航向随动云台     2 - 自由旋转云台（暂时不兼容 20240910）
gimbal_class: 0
# 云台俯仰角(注意要乘上100的比例尺-下视增稳航向随动云台生效)
gimbal_pitch: 0
#是否采用拼接功能  1---开启 0---关闭
mosaic_switch: 0


# 交互收飞参、图像的节点
zmq_addr_recv_frame: "tcp://192.168.100.101:18800"
zmq_addr_recv_aircraft: "tcp://192.168.100.101:19999"
# 下面这些地址每次部署到实飞平台都需要检查确认
# 给主程序发送飞参数据的ZMQ地址
zmq_addr_send_fk_param: "ipc:///tmp/external_pose"
# 给主程序发送图像数据的ZMQ地址
zmq_addr_send_frame: "ipc:///tmp/sensor_image"
# 从主程序接收机体定位结果的ZMQ地址
zmq_addr_recv_vis_res: "tcp://192.168.100.9:8848"
# 给外部发送机体定位结果的地址
zmq_addr_send_locate_res: "tcp://*:18888"
# 串口收飞参的地址、下视图像
serial_device: "/dev/ttyS7"
camera_device: "/dev/video40"
# 地图info地址
info_address: " /data/tnav/dmatch_v9/map/XJ_sat_L18_cut/info"
# 这么多 毫秒 未接收到成功的结果，则给飞控返回工作状态为5，同时转发gps位置给飞控
vis_res_fresh_tm_thres: 500
